version: '3.7'

services:
  server:
    build: .
    hostname: server
    container_name: Server
    networks:
      - default
  client0:
    build: .
    hostname: trainer0
    container_name: trainer0
    networks:
      - default
  client1:
    build: .
    hostname: trainer1
    container_name: trainer1
    networks:
      - default
  client2:
    build: .
    hostname: trainer2
    container_name: trainer2
    networks:
      - default
  client3:
    build: .
    hostname: trainer3
    container_name: trainer3
    networks:
      - default
  client4:
    build: .
    hostname: trainer4
    container_name: trainer4
    networks:
      - default
  client5:
    build: .
    hostname: trainer5
    container_name: trainer5
    networks:
      - default
  client6:
    build: .
    hostname: trainer6
    container_name: trainer6
    networks:
      - default
  client7:
    build: .
    hostname: trainer7
    container_name: trainer7
    networks:
      - default
  client8:
    build: .
    hostname: trainer8
    container_name: trainer8
    networks:
      - default
  client9:
    build: .
    hostname: trainer9
    container_name: trainer9
    networks:
      - default
  client10:
    build: .
    hostname: trainer10
    container_name: trainer10
    networks:
      - default
  client11:
    build: .
    hostname: trainer11
    container_name: trainer11
    networks:
      - default
  client12:
    build: .
    hostname: pokemon0
    container_name: pokemon0
    networks:
      - default
  client13:
    build: .
    hostname: pokemon1
    container_name: pokemon1
    networks:
      - default
  client14:
    build: .
    hostname: pokemon2
    container_name: pokemon2
    networks:
      - default
  client15:
    build: .
    hostname: pokemon3
    container_name: pokemon3
    networks:
      - default
  client16:
    build: .
    hostname: pokemon4
    container_name: pokemon4
    networks:
      - default
  client17:
    build: .
    hostname: pokemon5
    container_name: pokemon5
    networks:
      - default
  client18:
    build: .
    hostname: pokemon6
    container_name: pokemon6
    networks:
      - default
  client19:
    build: .
    hostname: pokemon7
    container_name: pokemon7
    networks:
      - default
  client20:
    build: .
    hostname: pokemon8
    container_name: pokemon8
    networks:
      - default
  client21:
    build: .
    hostname: pokemon9
    container_name: pokemon9
    networks:
      - default
  client22:
    build: .
    hostname: pokemon10
    container_name: pokemon10
    networks:
      - default
networks:
  default:
    driver: bridge